version: '3.8'
volumes:
  postgres-data:
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432
      - RAILS_SERVE_STATIC_FILES=true
    # volumes:
    #   - .:/Rails-Docker
    ports:
      - "3000:3000"
    depends_on:
      - db
